name: song-downloader

services:
  songdownloader:
    image: songdownloader:latest
    container_name: songdownloader
    restart: unless-stopped
    ports:
      - "8011:8011"
      # TODO: add volumes for songs
